#!/usr/bin/env ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'bundler/setup'
require 'bundler_api/env'
require 'bundler_api/metriks'
require 'puma/instrumented_cli'

cli = Puma::InstrumentedCLI.new(ARGV + %w(--config puma.rb))
cli.run
